In [1]:
import pandas as pd
import math
import numpy as np

In [2]:
#input = 'test_input1.txt'
#input = 'test_input1_1.txt'
input = 'input.txt'

In [3]:
def get_max_nof_cols(lines):
    max_cols = 0
    for line in lines:
        if len(line) > max_cols:
            max_cols = len(line)
    return max_cols

In [4]:
class ElfNumber:
  def __init__(self, first_pos, value):
    self.first_pos_row = first_pos[0]
    self.first_pos_col = first_pos[1]
    self.value = value

  def __str__(self):
    return f"ElfNumber: pos: ({self.first_pos_row},{self.first_pos_col}): {self.value}"
  
  def addValue(self, new_value):
    self.value = self.value * 10 + new_value
  
  def get_adjacent_positions(self):
    nof_places = math.floor(math.log10(self.value))
    adj = []
    # row above
    row_above = self.first_pos_row-1
    adj.append((row_above, self.first_pos_col-1))
    for i in range(0,nof_places+2):
      # add one too much
      adj.append((row_above, self.first_pos_col+i))
    # row itself
    adj.append((self.first_pos_row, self.first_pos_col-1))
    adj.append((self.first_pos_row, self.first_pos_col+nof_places+1))
    # row below
    row_below = self.first_pos_row+1
    adj.append((row_below, self.first_pos_col-1))
    for i in range(0,nof_places+2):
      # add one too much
      adj.append((row_below, self.first_pos_col+i))
    return adj
  
  def __repr__(self):
    return self.__str__()



In [5]:
def parse_line(row_num, row, playground,numbers):
    act_num = None
    for col, c in enumerate(row):
        if c.isdigit():
            if act_num == None:
                act_num = ElfNumber((row_num, col+1), int(c))
            else:
                act_num.addValue(int(c))
        else:
            if act_num != None:
                numbers.append(act_num)
                act_num = None
            if c != '.':
                playground[row_num, col+1] = 1
    if act_num != None:
        numbers.append(act_num)


In [6]:
with open(input) as f:
    lines = f.readlines()
    lines =  [line.replace("\n", "") for line in lines]
    nof_cols = get_max_nof_cols(lines) + 2
    nof_rows = len(lines) +2

    playground = np.zeros((nof_rows, nof_cols))
    numbers = []
    
    for i in range(0,nof_rows-2):
        parse_line(i+1,lines[i], playground, numbers)


    print(playground)
    print(numbers)

    sum = 0
    for number in numbers:
        val = 0
        for pos in number.get_adjacent_positions():
            val += playground[pos[0], pos[1]]
        if val > 0:
            sum += number.value
    print(sum)







[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[ElfNumber: pos: (1,14): 65, ElfNumber: pos: (1,34): 998, ElfNumber: pos: (1,46): 453, ElfNumber: pos: (1,84): 845, ElfNumber: pos: (1,89): 773, ElfNumber: pos: (1,117): 307, ElfNumber: pos: (1,124): 527, ElfNumber: pos: (1,138): 541, ElfNumber: pos: (2,24): 125, ElfNumber: pos: (2,38): 331, ElfNumber: pos: (2,69): 30, ElfNumber: pos: (2,72): 76, ElfNumber: pos: (2,93): 861, ElfNumber: pos: (2,113): 298, ElfNumber: pos: (2,133): 700, ElfNumber: pos: (3,17): 942, ElfNumber: pos: (3,31): 874, ElfNumber: pos: (3,44): 407, ElfNumber: pos: (3,50): 558, ElfNumber: pos: (3,65): 752, ElfNumber: pos: (3,75): 196, ElfNumber: pos: (3,79): 274, ElfNumber: pos: (3,83): 240, ElfNumber: pos: (3,87): 345, ElfNumber: pos: (3,102): 105, ElfNumber: pos: (3,124): 164, ElfNumber: pos: (3,138): 466, ElfNumber: pos: (4,24): 593, ElfNumber: pos: (4,38): 51

In [7]:
a = ElfNumber((2,3),9)
a.addValue(7)
a.addValue(2)

b = ElfNumber((6,7),1)
b.addValue(2)
b.addValue(3)

print(a)
print(b)
#print(a.get_adjacent_positions())




ElfNumber: pos: (2,3): 972
ElfNumber: pos: (6,7): 123
